// Configuration file for dropdown lists
// Add your Section and Product lists here
// These can be easily edited and expanded

const CONFIG = {
    // Section list - add your sections here
    sections: [
        'MMP1',
        'MMP2',
        'FIP1',
        'FICP',
        'CMX',
        'KIT',
        'PAK',
        'BST1',
        'FNC',
        'CNL',
        'DFL',
        'BST2',
    ],
    
    // Product list - add your products here
    products: [
      'ANBL',
        'ANCB',
        'ANKHS',
        'ANKN',
        'ERBL',
        'ERCN',
        'ERSMS',
        'ERVS',
        'MACB',
        'WAML',
        'WAVS',
        'VFCB',
        'VFCHL',
        'VFCLM',
        'VFLMT',
        'VFLSP',
        'VFPB',
        'VFSIC',
        'VFSMS',
        'VFSSS',
        'VFVS',
        'WABL',
        'WACB',
        'WRBL',
        'WRML',
        'BSCD',
        'BSCS',
        'BSHD',
        'BSHSC',
        'BSHS',
        'WRHMO',
        'VFSIF',
        'CNCCR',
        'CNCH',
        'CNCLE',
        'CNCNL',
        'CNHC',
        'CNHD',
        'CNLGR',
        'CNPLE',
        'CNTCR',
        'CSG',
        'WRCKH',
        'ERBPC',
        'ERBPT',
        'ERFCB',
        'ERGC',
        'ERLM',
        'ERSPH',
        'WRSBN',
        'NYCH',
        'NYCK',
        'NYHD',
        'VFHSC',
        'VFHSG',
        'SDBML',
        'VFBPR',
        'SDCBH',
        'SDDS',
        'SDNBH',
        'VFPPR',
        'SDSCH',
        'SDTBH',
        'SDVBH',
        'SDVSS',
        'VFHCB',
        'VFBBG',
        'VFBBN',
        'VFBMB',
        'VFCCJ',
        'VFCD',
        'VFCHD',
        'VFCHO',
        'VFCKH',
        'VFSWH',
        'VFCNH',
        'VFCSK',
        'VFCTC',
        'VFFCB',
        'VFHCS',
        'VFPHD',
        'VFHDC',
        'VFHMS',
        'VFLDC',
        'VFPCS',
        'VFPMS',
        'VFPRN',
        'VFPTC',
        'VFPTL',
        'VFSAL',
        'WRBBA',
        'WRBKH',
        'WRCBA',
        'WRCHO',
        'WRCS',
        'WREMB',
        'WRFHD',
        'WRLW',
        'WRMCB',
        'WRPL',
        'WRPS',
        'WRSCS',
        'WRSWH',


    ],
    
    // Optional: Add more lists as needed
    // SKU: [...],
    // WorkUnit: [...],
    // Oprt: [...],
    // MTE: [...]
};

// For backward compatibility
const SECTIONS = CONFIG.sections;
const PRODUCTS = CONFIG.products;